# Generated by Django 5.0.3 on 2024-07-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_stock_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_owed', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Factory_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Kg_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Purchases_Account',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Quantity_Stored',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Retail_pice',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Sales_Account',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Supplier_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Wholesale_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product_location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
    ]
