# Generated by Django 5.0.3 on 2024-08-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_creditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='factory_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_supplier',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='recorded_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='retail_prices',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='supplier_prices',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='units_of_measure',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='wholesale_pice',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posApp.store'),
        ),
    ]
