# Generated by Django 5.0.3 on 2024-08-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_store_remove_stock_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product_name', 'store')},
        ),
    ]
